# Generated by Django 5.0.7 on 2024-08-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="restaurant",
            old_name="backgroud_image",
            new_name="background_image",
        ),
        migrations.AlterField(
            model_name="user",
            name="type_user",
            field=models.CharField(
                choices=[("SUPPLIER", "Restaurant Owner"), ("CUSTOMER", "Costumer")],
                default="CUSTOMER",
                max_length=8,
            ),
        ),
    ]
