# Generated by Django 5.0.7 on 2024-08-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0002_rename_backgroud_image_restaurant_background_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="type_table",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="address",
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="average_price_dollars",
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="phone",
            field=models.CharField(default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="restaurant",
            name="site",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="table",
            name="seats",
            field=models.IntegerField(choices=[(4, "4"), (8, "8")]),
        ),
    ]
