# Generated by Django 5.0.7 on 2024-08-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_remove_table_type_table_restaurant_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[(0, "Waiting"), (1, "Cancelled"), (2, "Completed")],
                default="Waiting",
                max_length=1,
            ),
        ),
    ]
