# Generated by Django 5.0.7 on 2024-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="menu",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Waiting"), (1, "Cancelled"), (2, "Comfirmed")], default=0
            ),
        ),
    ]
