# Generated by Django 5.0.7 on 2024-08-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_restaurant_menu_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="background_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/background/"
            ),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="images/logo/"),
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="menu",
            field=models.ImageField(blank=True, null=True, upload_to="images/menu/"),
        ),
        migrations.AlterField(
            model_name="user",
            name="type_user",
            field=models.CharField(
                choices=[("SUPPLIER", "Restaurant Owner"), ("CUSTOMER", "Customer")],
                default="CUSTOMER",
                max_length=8,
            ),
        ),
    ]
